// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/28/2026, 11:44:00 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/sysadmin/dev/ansiventory-ui/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/plugins/**/*.{js,ts,mjs}","/home/sysadmin/dev/ansiventory-ui/frontend/composables/**/*.{js,ts,mjs}","/home/sysadmin/dev/ansiventory-ui/frontend/utils/**/*.{js,ts,mjs}","/home/sysadmin/dev/ansiventory-ui/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sysadmin/dev/ansiventory-ui/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;