---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansiventory-frontend
  namespace: ansiventory
  labels:
    app: ansiventory-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ansiventory-frontend
  template:
    metadata:
      labels:
        app: ansiventory-frontend
    spec:
      imagePullSecrets:
        - name: ansiventory-secrets
      containers:
        - name: frontend
          image: bauhaussistemas/ansiventory-ui-frontend:latest  # ajuste para seu registry
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_API_BASE
              value: "http://ansiventory-backend.ansiventory.svc.cluster.local"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ansiventory-frontend
  namespace: ansiventory
spec:
  selector:
    app: ansiventory-frontend
  ports:
    - port: 80
      targetPort: 3000
