apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansiventory
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:sysadmin-systems/ansiventory-ui.git
    targetRevision: master
    path: infra/k8s
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ansiventory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
