---
# SecretStore — aponta para o OpenBao
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: openbao-backend
#   namespace: ansiventory
# spec:
#   provider:
#     vault:
#       server: "https://bao.bauhaus.cloud:8200"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "ansiventory"
#           serviceAccountRef:
#             name: ansiventory-backend

---
# ExternalSecret — puxa os secrets do OpenBao e cria um Secret k8s
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ansiventory-secrets
  namespace: ansiventory
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: ansiventory-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: POSTGRES_DB
    - secretKey: .dockerconfigjson
      remoteRef:
        key: external-secrets/dockerhub
        property: dockerconfigjson
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: POSTGRES_HOST
