---
# SecretStore — aponta para o OpenBao
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: openbao-backend
#   namespace: ansiventory
# spec:
#   provider:
#     vault:
#       server: "https://bao.bauhaus.cloud:8200"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "ansiventory"
#           serviceAccountRef:
#             name: ansiventory-backend

---
# ExternalSecret — puxa os secrets do OpenBao e cria um Secret k8s
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ansiventory-secrets
  namespace: ansiventory
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: ansiventory-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: external-secrets/argocd/ansiventory
          metadataPolicy: None
          property: POSTGRES_PASSWORD
        secretKey: POSTGRES_PASSWORD
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: external-secrets/argocd/ansiventory
          metadataPolicy: None
          property: POSTGRES_USER
        secretKey: POSTGRES_USER
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: external-secrets/argocd/ansiventory
          metadataPolicy: None
          property: POSTGRES_DB
        secretKey: POSTGRES_DB
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: external-secrets/dockerhub
          metadataPolicy: None
          property: dockerconfigjson
        secretKey: .dockerconfigjson
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: external-secrets/argocd/ansiventory
          metadataPolicy: None
          property: POSTGRES_HOST
        secretKey: POSTGRES_HOST