---
# SecretStore — aponta para o OpenBao
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: openbao-backend
#   namespace: ansiventory
# spec:
#   provider:
#     vault:
#       server: "https://bao.bauhaus.cloud:8200"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "ansiventory"
#           serviceAccountRef:
#             name: ansiventory-backend

---
# ExternalSecret — puxa os secrets do OpenBao e cria um Secret k8s
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ansiventory-secrets
  namespace: ansiventory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: ansiventory-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: username
    - secretKey: POSTGRES_DB
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: dbname
    - secretKey: REG_CRED
      remoteRef:
        key: external-secrets/argocd/ansiventory
        property: dockerconfigjson
        type: kubernetes.io/dockerconfigjson
